version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db-product
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword       # Change this!
      MYSQL_DATABASE: productcatalog              # Optional
      MYSQL_USER: ecommerce                      # Optional
      MYSQL_PASSWORD: ecompassword              # Optional
    ports:
      - "3308:3308"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
volumes:
  mysql-data:
  redis-data: